<a href="https://colab.research.google.com/github/LaskaMaharjan/MachineLearningg/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Introduction to Numpy

# Introduction To Numpy

What will we cover?
- Creating arrays ✅
-Multidimensional array✅
-Randomly Generated arrays✅
-Element wise operation
-Summarizing the operations



### Single Dimensional Array

In [ ]:
import numpy as np


In [ ]:
#create an array with all the elements to be zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
#creating an array with all elements 1
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
#create an array of size 10 with all elements 3
np.full(10,3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [ ]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [ ]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
#creating an array  with evenly spaced numbers within a specified range
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

### Multi dimensional arrays


In [ ]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((3,5))


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a[0, 1] =20
a

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [ ]:
a[1, 0]= 11
a


array([[ 1, 20,  3],
       [11,  5,  6],
       [ 7,  8,  9]])

In [ ]:
a[2]=[1,1,1]
a


array([[ 1, 20,  3],
       [11,  5,  6],
       [ 1,  1,  1]])

In [ ]:
a[:, 2]=[2, 2, 2]
a

array([[ 1, 20,  2],
       [11,  5,  2],
       [ 1,  1,  2]])

In [ ]:
np.full(3, 10)

array([10, 10, 10])

In [ ]:
np.full(3, 3, 10)

TypeError: Cannot interpret '10' as a data type

In [ ]:
np.full((3,3),10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

### Randomly Generated Arrays

-Numpy can create arrays filled with random numbers
-To ensure the reproducibility, you can set a seed using ```np.random.seed()```. It will generate the exact same random numbers for each executions.
-If you remove or change the seed values,the sequence of random numbers will be changed.

In [ ]:
np.random.rand(5)

array([0.92026705, 0.36218054, 0.16394461, 0.89149492, 0.80053265])

In [ ]:
np.random.seed(80)
np.random.rand(5)

array([0.52191572, 0.69940637, 0.26986897, 0.67448187, 0.90807208])

In [ ]:
np.random.rand(80)
np.random.rand(5)

array([0.46609352, 0.19572576, 0.30468262, 0.5963392 , 0.8735609 ])

In [ ]:
np.random.randn(5, 2)

array([[-1.03446493,  0.66424004],
       [-1.13937438, -0.89472205],
       [-0.2207972 , -0.43007258],
       [ 1.19972246,  0.1222967 ],
       [ 0.54794733, -0.52658091]])

In [ ]:
np.random.randint(low=0, high=100, size=(5,2))

array([[ 7, 69],
       [96, 56],
       [15,  3],
       [94, 39],
       [51, 94]])

### Element wise operation on entire arrays elemnent by element

In [1]:
import numpy as np
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [2]:
b=(10+(a*2))
b

array([10, 12, 14, 16, 18])

In [3]:
a #comparison operations

array([0, 1, 2, 3, 4])

In [4]:
a >= 2

array([False, False,  True,  True,  True])

In [5]:
a>b

array([False, False, False, False, False])

In [6]:
#summarizing of the data
#Numpy provides functions for summarizing array data
a

array([0, 1, 2, 3, 4])

In [7]:
a.std()

1.4142135623730951

In [8]:
a.min()

0

In [9]:
a.max()

4

In [10]:
a.mean()

2.0

In [11]:
a.sum()

10